import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import './globals.css'

import { UserProvider } from './context/userContext';
import Header from './components/Header';
import Navigation from './navigation/Navigation';

const inter = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <UserProvider>
        <html lang="en">
            <body className={inter.className}>
                <header>
                    <Header title="Pet Life" />
                    <nav>
                        <Navigation />
                    </nav>
                </header>

                  {children}
            </body>
        </html>
      </UserProvider>
  )
}
